### ISSUE TITLE
[Feature Request]英文支持

### ISSUE THREAD

**Issue by Fireond** [euxcet/thulearn2018#12]
是否可以根据网络学堂的语言设置来自动设置课程名字为英文，有些作业中包含中文路径会有bug

**Comment by YuruiHong** [comment]
之前考虑过英文支持的问题，但是没有想到比较好的方案，主要是考虑到如果切换中英文实现为修改对应文件夹名，则之前积累的shell补全很多会无效；如果用链接等形式实现为中英文入口各一个，则目录多了一倍，在GUI中索引不方便；另外，如果要实现这个切换功能，我认为不应该用远端网络学堂设置的语言来判定，而应该在本地设置，否则可能导致许多不希望的变动。

希望你或者有相同需求的其他同学能对语言切换的实现提出更好的设计。至于你遇到的中文路径问题，我认为可行的解决方法是根据自己的需要将代码作业等项目直接软链接到纯英文路径下运行，这样写完依然可以直接`learn submit`。而且因为网络学堂只有课程名是提供翻译的，具体课程文件没有，也即全英文无法实现，我认为大部分使用`thulearn2018`的同学使用的都是支持中文的shell。（

**Comment by Fireond** [comment]
明白了，感谢，以及有什么好的办法解决路径包含空格的问题吗

**Comment by YuruiHong** [comment]
不太确定你指的是什么场景，如果是在shell中，可以参考 https://www.ibm.com/docs/en/jfsm/1.1.2.1?topic=errors-white-spaces-brackets-file-paths
