### ISSUE TITLE
无法正确处理同名课程

### ISSUE THREAD

**Issue by YuruiHong** [euxcet/thulearn2018#6]
经测试，当学期中出现两门名称完全相同的课程时，`thulearn2018`无法进行正确区分，而会合并两门课程的`file`和`homework`文件夹。因为这是一个简单的命令行工具，课程名直接作为文件夹名，无法将ID与显示分离，故解决该问题需要改动文件夹命名方式，我想到的方案是在课程名后默认添加任课教师，不知道有无其他建议。

**Comment by thuliu-yt16** [comment]
能否get到课程ID? 这个应该是唯一的

**Comment by YuruiHong** [comment]
> 能否get到课程ID? 这个应该是唯一的

目前的问题不在获取课程时进行区分，而是在存储时。现在的每门课程相关文件存在`<课程名>`文件夹下，所以下载时两门课都会存到这个路径。个人认为使用ID命名文件夹非常不直观，而且理论上应该没有课程名称和任课教师均相同的不同课程，故给出上述解决方法。目前是征求可读性较强且避免重复的课程文件夹命名方式。

**Comment by thuliu-yt16** [comment]
可以在课程名后增加课程ID或老师，或许某些博士生和硕士生课程具有相同的课程名称和任课教师
