### ISSUE TITLE
Error: 密码错误

### ISSUE THREAD

**Issue by Ethkuil** [euxcet/thulearn2018#9]
先后尝试了 设置+`learn ddl` 4次，都提示“密码错误”。

我分别尝试了 字母+数字的用户名 与 纯学号 的用户名，都是如此。并不是密码输错了，因为

1. 密码是我从密码管理工具里复制出来的，刚刚又再次验证了这对账密是能登陆网络学堂的。
2. 我在 `.thulearn2018-user.txt` 文件里看到了我的账密，是正确的。

顺便要吐槽，一个设置密码怎么没有“再次输入”来防止输错呀……

**Comment by Ethkuil** [comment]
以及，可以像 git 那样单独配置某个选项吗？比如清华账号改了密码，就只改密码；目录迁移了，就只改目录。

**Comment by Ethkuil** [comment]
补充信息：

thulearn2018 version: `pip install thulearn2018` 所得的 v2.2.1，发现其发布时间是 Nov 2, 2021 orz. 我盲猜这就是原因

python version: 3.9.5

os: Windows 11

**Comment by YuruiHong** [comment]
确实是这样的，因为我刚接手项目，还没有拿到PyPI的提交权限，导致`pip install`下载的还是2021年的版本，由于网络学堂改版导致一些URL发生了变化而不可用。目前推荐使用从GitHub安装的方法。

关于配置项，目前既然你已经找到了.thulearn2018-user.txt，那就可以直接在这里进行更改。其实当时计划对配置文件可能会有修改，因此没有在`README.md`中加上它们的默认位置。新版Windows应该默认在`%APPDATA%\thulearn2018`下，而类UNIX根据XDG规范在`$HOME/.config/thulearn1028`下。2021年dotfile的位置和命名应该不太推荐。（

**Comment by Ethkuil** [comment]
Okk，期待~

**Comment by YuruiHong** [comment]
Update: 已向PyPI上传最新版本
